spring:
  application:
    name: calculations

  datasource:
    url: jdbc:postgresql://localhost:5435/service3_db
    username: payrolluser
    password: payrollpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: salary-calculation-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

server:
  port: 8082
  application:
    handbookUrl: http://localhost:8081