spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: salary-calculation-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: isys.labs.calculations.dto.SalaryCalculationEvent
        spring.json.trusted.packages: isys.labs.calculations.dto
  application:
    name: calculations

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/service3_db}
    username: ${SPRING_DATASOURCE_USERNAME:payrolluser}
    password: ${SPRING_DATASOURCE_PASSWORD:payrollpass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public

server:
  port: 8082
  application:
    handbookUrl: http://localhost:8081