spring:
  application:
    name: handbook

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/service2_db}
    username: ${SPRING_DATASOURCE_USERNAME:refuser}
    password: ${SPRING_DATASOURCE_PASSWORD:refpass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public
server:
  port: 8081